spring.application.name: aggregatr
metrics.path.app: aggregatr
rest.api.urls.to.list: .*ingredients.*
stubrunner:
  #skip-local-repo: false
  #work-offline: true
  use-microservice-definitions: true
  stubs:
    repository.root: "http://nexus.uservices:8081/nexus/content/repositories/releases/"